sudo: required
language: node_js 
node_js: 
  - "9"
services:
  - docker

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com

script:
  - docker build -t pram25/docker_client ./frontend_heroku;
  - docker tag pram25/docker_client registry.heroku.com/$HEROKU_APP_NAME/web;

deploy:
  provider: script
  script: 
    # push to dockerhub & heroku 
    docker push pram25/docker_client;
    docker push registry.heroku.com/$HEROKU_APP_NAME/web;
    heroku container:release web --app $HEROKU_APP_NAME;
  on: 
    branch: master
